# .streamlit/secrets.toml

[connections.supabase]
dialect = "postgresql"
# ข้อมูลที่ดึงมาจาก URI:
host = "db.iqlfdvxgugadtwtgmesv.supabase.co" 
port = 5432
database = "postgres" 
username = "postgres"
password = "9upH+R6%RujENP4" # ⬅️ ใส่รหัสผ่านของคุณตรงนี้