# .streamlit/secrets.toml
# ต้องเปลี่ยนค่าเหล่านี้ให้ตรงกับ Project ของคุณ
SUPABASE_URL = "https://qkipiuxqeiwgtmhmvfyz.supabase.co" 
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraXBpdXhxZWl3Z3RtaG12Znl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTM0NjYsImV4cCI6MjA3NDg4OTQ2Nn0.y-l0P-ghAIGL78heZfq9woy7DdhYPn71G9HmoMnTRAw"
SUPABASE_BUCKET = "streamlit-demo" # ชื่อ Bucket Storage ที่คุณสร้างไว้

[connections.supabase]
url = "https://qkipiuxqeiwgtmhmvfyz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraXBpdXhxZWl3Z3RtaG12Znl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTM0NjYsImV4cCI6MjA3NDg4OTQ2Nn0.y-l0P-ghAIGL78heZfq9woy7DdhYPn71G9HmoMnTRAw"          # ใช้ service_role key เช่นกัน